name: Build and Export Godot Project

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  import-assets:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Import assets (Godot editor)
        run: godot --headless --verbose --editor --quit

  export-linux:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci
    needs: import-assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Godot Export Templates
        run: |
          apt-get update && apt-get install -y curl
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          curl -L https://downloads.tuxfamily.org/godotengine/4.4.1/export_templates/godot_export_templates_4.4.1.stable.zip -o godot_export_templates.zip
          unzip godot_export_templates.zip -d ~/.local/share/godot/export_templates/4.4.1.stable
          rm godot_export_templates.zip
      - name: Export Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(pwd)/build"
          godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/${{ secrets.EXPORT_NAME }}.x86_64"
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ secrets.EXPORT_NAME }}-linux
          path: build/linux

  export-windows:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci
    needs: import-assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Godot Export Templates
        run: |
          apt-get update && apt-get install -y curl
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          curl -L https://downloads.tuxfamily.org/godotengine/4.4.1/export_templates/godot_export_templates_4.4.1.stable.zip -o godot_export_templates.zip
          unzip godot_export_templates.zip -d ~/.local/share/godot/export_templates/4.4.1.stable
          rm godot_export_templates.zip
      - name: Export Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(pwd)/build"
          godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/${{ secrets.EXPORT_NAME }}.exe"
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ secrets.EXPORT_NAME }}-windows
          path: build/windows

  export-mac:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci
    needs: import-assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Godot Export Templates
        run: |
          apt-get update && apt-get install -y curl
          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
          curl -L https://downloads.tuxfamily.org/godotengine/4.4.1/export_templates/godot_export_templates_4.4.1.stable.zip -o godot_export_templates.zip
          unzip godot_export_templates.zip -d ~/.local/share/godot/export_templates/4.4.1.stable
          rm godot_export_templates.zip
      - name: Export macOS Build
        run: |
          mkdir -v -p build/mac
          EXPORT_DIR="$(pwd)/build"
          godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/${{ secrets.EXPORT_NAME }}.zip"
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ secrets.EXPORT_NAME }}-mac
          path: build/mac
